version: '3'

services:
  web2-docker:
    build: ./docker
    image: web2-docker
    ports:
      - "8888:8888"
      - "4343:4343"
    volumes:
      - ./www:/var/www
    links:
      - mysql

  mysql:
    image: mariadb:10.5.9
    ports:
      - "3306:3306"
    volumes:
      - ./db:/var/lib/mysql
    environment:
      MYSQL_SERVERNAME: localhost
      MYSQL_USERNAME: root
      MYSQL_ROOT_PASSWORD: root

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    links:
      - mysql
    ports:
      - "8800:8800"
    volumes:
      - ./docker/php/php.ini:/usr/local/etc/php/php.ini
    environment:
      MYSQL_SERVERNAME: localhost
      MYSQL_USERNAME: root
      MYSQL_ROOT_PASSWORD: root
      PMA_HOST: mysql
      UPLOAD_LIMIT: 128M
 
#   volumes:
#     data:

#   networks:
#     default:
#       external: true
#       name: nginx_proxy_manager
